<a href="https://colab.research.google.com/github/zenyonki/enigh_caract_hogares/blob/main/enigh_caract_hogares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Análisis "Características de las viviendas" de la ENIGH 2024

##Importación de librerías y tablas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [97]:
#Este índice corresponde a los nombres de las tablas proporcionadas en el paquete de datos que brinda el INEGI.
#Los datos se encuntran disponibles en:
#https://www.inegi.org.mx/programas/enigh/nc/2022/

indice_tablas = pd.read_csv('/content/0_indice_tablas_enigh2024_ns.csv', encoding='utf-8-sig')
indice_tablas.reset_index(drop=True, inplace=True)
indice_tablas

,Encuesta Nacional de Ingresos y Gastos de los Hogares 2024 Nueva Serie\t,Unnamed: 1
0,\t,NaN
1,Nombre de archivo\tTítulo de Tablas,NaN
2,conjunto_de_datos_agro_enigh_2024_ns\t,Negocios agropecuarios de los hogares
3,conjunto_de_datos_agroconsumo_enigh_2024_ns,"Destino, cantidad y valor de los productos del..."
4,conjunto_de_datos_agrogasto_enigh_2024_ns,Gasto que realiza el negocio del Hogar
5,conjunto_de_datos_agroproductos_enigh_2024_ns,Productos de los negocios agrícolas del hogar
6,conjunto_de_datos_concentradohogar_enigh_2024_...,Principales variables por hogar
7,conjunto_de_datos_erogaciones_enigh_2024_ns\t,Erogaciones de capital por hogar
8,conjunto_de_datos_gastoshogar_enigh_2024_ns\t,Gastos en los hogares
9,conjunto_de_datos_gastospersona_enigh_2024_ns\t,Gastos realizados en el hogar a nivel integrante
10,conjunto_de_datos_gastotarjetas_enigh_2024_ns\t,Gastos realizados por el hogar y que fueron cu...
11,conjunto_de_datos_hogares_enigh_2024_ns\t,Características de los hogares que habitan los...
12,conjunto_de_datos_ingresos_enigh_2024_ns\t,Ingresos y percepciones financieras y de capit...
13,conjunto_de_datos_ingresos_jcf_enigh_2024_ns,Ingresos del programa Jóvenes Construyendo el ...
14,conjunto_de_datos_noagro_enigh_2024_ns\t,Negocios no agropecuarios de los hogares
15,conjunto_de_datos_noagroimportes_enigh_2024_ns,Importe de los productos de los negocios no ag...
16,conjunto_de_datos_poblacion_enigh_2024_ns,\tCaracterísticas sociodemográficas de los int...
17,conjunto_de_datos_trabajos_enigh_2024_ns\t,Condición de actividad de los integrantes del ...
18,conjunto_de_datos_viviendas_enigh_2024_ns\t,Características de las viviendas que habitan l...

In [ ]:
#Se importa la tabla "Características de las viviendas que habitan..." para su análsis.

caract_hogares = pd.read_csv('/content/conjunto_de_datos_viviendas_enigh2024_ns.csv', encoding='utf-8-sig')
caract_hogares.reset_index(drop=True, inplace=True)
caract_hogares.sample(10)

,folioviv,tipo_viv,mat_pared,mat_techos,mat_pisos,antiguedad,antigua_ne,cocina,cocina_dor,cuart_dorm,...,tot_hom,tot_muj,tot_hog,ubica_geo,tam_loc,est_socio,est_dis,upm,factor,procaptar
9176,361137818,1,8,10,1,9,NaN,2,NaN,1,...,0,1,1,3003,4,1,52,1137,14,0
12015,501466902,1,8,10,2,,1.0,1,2.0,1,...,1,0,1,5002,1,2,71,1466,268,0
87880,3200371302,1,8,3,2,20,NaN,1,1.0,3,...,4,4,1,32007,3,2,670,10371,164,0
68981,2468116923,1,7,3,2,40,NaN,1,2.0,3,...,1,2,1,24047,4,2,489,8116,220,0
39196,1364656410,1,8,10,3,32,NaN,1,2.0,2,...,0,2,1,13084,4,2,246,4656,348,0
39338,1404667511,1,8,10,2,16,NaN,1,2.0,4,...,2,2,1,14024,2,3,265,4667,868,0
82197,3009782002,1,3,10,3,42,NaN,1,2.0,2,...,0,1,1,30028,1,3,619,9782,1435,0
37980,1304582817,1,8,10,2,50,NaN,1,2.0,1,...,0,2,1,13076,3,3,257,4582,220,0
90103,3260583815,1,7,8,2,44,NaN,1,2.0,1,...,1,0,1,32042,4,2,680,10583,179,0
80059,2909494019,1,8,10,2,10,NaN,1,1.0,2,...,4,3,1,29007,3,1,599,9494,111,0

In [ ]:
caract_hogares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90324 entries, 0 to 90323
Data columns (total 82 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   folioviv    90324 non-null  int64
 1   tipo_viv    90324 non-null  object
 2   mat_pared   90324 non-null  int64
 3   mat_techos  90324 non-null  int64
 4   mat_pisos   90324 non-null  object
 5   antiguedad  90324 non-null  object
 6   antigua_ne  12278 non-null  float64
 7   cocina      90324 non-null  int64
 8   cocina_dor  84638 non-null  float64
 9   cuart_dorm  90324 non-null  int64
 10  num_cuarto  90324 non-null  int64
 11  lugar_coc   90324 non-null  int64
 12  agua_ent    90324 non-null  int64
 13  ab_agua     86149 non-null  float64
 14  agua_noe    4175 non-null   float64
 15  dotac_agua  86149 non-null  float64
 16  excusado    90324 non-null  int64
 17  uso_compar  88826 non-null  float64
 18  sanit_agua  88826 non-null  float64
 19  biodigest   88826 non-null  float64
 20  bano_comp   90324 non-null  object
 21  bano_excus  90324 non-null  object
 22  bano_regad  90324 non-null  object
 23  drenaje     90324 non-null  int64
 24  disp_elect  90324 non-null  int64
 25  focos       90324 non-null  object
 26  focos_ahor  90324 non-null  object
 27  combus      90324 non-null  object
 28  fogon_chi   13264 non-null  float64
 29  eli_basura  90324 non-null  int64
 30  tenencia    90324 non-null  int64
 31  renta       90324 non-null  object
 32  estim_pago  90324 non-null  object
 33  pago_viv    90324 non-null  object
 34  pago_mesp   19522 non-null  float64
 35  tipo_adqui  65964 non-null  float64
 36  viv_usada   17857 non-null  float64
 37  finan_1     10039 non-null  float64
 38  finan_2     1479 non-null   float64
 39  finan_3     78 non-null     float64
 40  finan_4     92 non-null     float64
 41  finan_5     2538 non-null   float64
 42  finan_6     1513 non-null   float64
 43  finan_7     2007 non-null   float64
 44  finan_8     42353 non-null  object
 45  num_dueno1  65964 non-null  float64
 46  hog_dueno1  65964 non-null  float64
 47  num_dueno2  3133 non-null   float64
 48  hog_dueno2  3133 non-null   float64
 49  escrituras  65964 non-null  float64
 50  lavadero    90324 non-null  int64
 51  fregadero   90324 non-null  int64
 52  regadera    90324 non-null  int64
 53  tinaco_azo  90324 non-null  int64
 54  cisterna    90324 non-null  int64
 55  pileta      90324 non-null  int64
 56  calent_sol  90324 non-null  int64
 57  calent_gas  90324 non-null  int64
 58  calen_lena  90324 non-null  int64
 59  medid_luz   90324 non-null  int64
 60  bomba_agua  90324 non-null  int64
 61  tanque_gas  90324 non-null  int64
 62  aire_acond  90324 non-null  int64
 63  calefacc    90324 non-null  int64
 64  p_grietas   90324 non-null  int64
 65  p_pandeos   90324 non-null  int64
 66  p_levanta   90324 non-null  int64
 67  p_humedad   90324 non-null  int64
 68  p_fractura  90324 non-null  int64
 69  p_electric  90324 non-null  int64
 70  p_tuberias  90324 non-null  int64
 71  tot_resid   90324 non-null  int64
 72  tot_hom     90324 non-null  int64
 73  tot_muj     90324 non-null  int64
 74  tot_hog     90324 non-null  int64
 75  ubica_geo   90324 non-null  int64
 76  tam_loc     90324 non-null  int64
 77  est_socio   90324 non-null  int64
 78  est_dis     90324 non-null  int64
 79  upm         90324 non-null  int64
 80  factor      90324 non-null  int64
 81  procaptar   90324 non-null  int64
dtypes: float64(24), int64(45), object(13)
memory usage: 56.5+ MB

##Limpieza y modelado de datos

In [ ]:
#Se estandarizan los datos contenidos en la columna "folioviv".

caract_hogares['folioviv'] = caract_hogares['folioviv'].astype(str)
caract_hogares['folioviv'] = caract_hogares['folioviv'].apply(
    lambda x: '0' + x if len(x) == 9 else x
)
caract_hogares['folioviv'].str.len().value_counts()

folioviv
10    90324
Name: count, dtype: int64

In [ ]:
caract_hogares.sample(10)

,folioviv,tipo_viv,mat_pared,mat_techos,mat_pisos,antiguedad,antigua_ne,cocina,cocina_dor,cuart_dorm,...,tot_hom,tot_muj,tot_hog,ubica_geo,tam_loc,est_socio,est_dis,upm,factor,procaptar
56520,2006721302,1,8,10,3,10,NaN,1,2.0,2,...,4,1,1,20367,3,1,414,6721,617,0
79712,2869451920,2,8,5,1,,1.0,1,2.0,3,...,2,2,1,28039,4,1,593,9451,176,0
34627,1204271305,1,8,10,2,40,NaN,1,2.0,6,...,2,2,1,12001,3,2,223,4271,588,0
87346,3160346615,1,8,10,2,12,NaN,2,NaN,3,...,3,1,1,31079,4,1,659,10346,79,0
48195,1705784701,2,8,10,3,,1.0,1,1.0,1,...,2,2,1,17008,2,3,355,5784,301,0
11006,0401392301,1,8,10,2,2,NaN,1,2.0,2,...,2,2,1,4005,3,2,53,1392,133,0
40870,1414936602,1,8,10,2,30,NaN,1,2.0,3,...,3,1,1,14120,1,1,285,4936,1190,0
13294,0501676305,7,8,10,3,50,NaN,1,1.0,1,...,2,1,1,5030,1,3,89,1676,239,0
48375,1705816803,2,8,10,3,,1.0,1,2.0,1,...,2,1,1,17011,1,3,347,5816,243,0
34468,1164245608,1,6,4,2,24,NaN,1,2.0,2,...,2,1,1,11045,4,1,218,4245,210,0

In [ ]:
#Creación de diccionario para crear nueva columna "entidad"
#Creación de columna "entidad"

entidades_mexico = {
    "01": "Aguascalientes",
    "02": "Baja California",
    "03": "Baja California Sur",
    "04": "Campeche",
    "05": "Coahuila",
    "06": "Colima",
    "07": "Chiapas",
    "08": "Chihuahua",
    "09": "Ciudad de México",
    "10": "Durango",
    "11": "Guanajuato",
    "12": "Guerrero",
    "13": "Hidalgo",
    "14": "Jalisco",
    "15": "México",
    "16": "Michoacán",
    "17": "Morelos",
    "18": "Nayarit",
    "19": "Nuevo León",
    "20": "Oaxaca",
    "21": "Puebla",
    "22": "Querétaro",
    "23": "Quintana Roo",
    "24": "San Luis Potosí",
    "25": "Sinaloa",
    "26": "Sonora",
    "27": "Tabasco",
    "28": "Tamaulipas",
    "29": "Tlaxcala",
    "30": "Veracruz",
    "31": "Yucatán",
    "32": "Zacatecas"
}


caract_hogares['entidad'] = caract_hogares['folioviv'].str[:2].map(entidades_mexico)
caract_hogares.sample(10)

,folioviv,tipo_viv,mat_pared,mat_techos,mat_pisos,antiguedad,antigua_ne,cocina,cocina_dor,cuart_dorm,...,tot_muj,tot_hog,ubica_geo,tam_loc,est_socio,est_dis,upm,factor,procaptar,entidad
42522,1515137701,2,8,10,2,,1.0,1,2.0,1,...,1,1,15037,1,2,292,5137,2145,0,México
87045,3160332714,1,8,10,2,25,NaN,1,2.0,2,...,3,1,31050,4,2,667,10332,89,0,Yucatán
71699,2508539801,1,8,10,3,,1.0,1,2.0,2,...,2,1,25012,1,4,518,8539,286,0,Sinaloa
88694,3200487020,1,8,10,2,80,NaN,1,2.0,2,...,1,1,32036,2,3,669,10487,229,0,Zacatecas
67014,2407876823,1,8,10,2,10,NaN,1,2.0,3,...,5,1,24020,2,2,494,7876,357,0,San Luis Potosí
83927,3069983609,2,7,3,2,50,NaN,1,2.0,2,...,1,1,30060,4,1,627,9983,632,0,Veracruz
44607,1565407920,1,8,10,2,20,NaN,1,2.0,2,...,3,1,15088,4,2,302,5407,309,0,México
40969,1414958704,1,8,10,3,20,NaN,1,2.0,1,...,1,1,14120,1,4,268,4958,1327,0,Jalisco
14159,0501849617,1,8,7,2,15,NaN,1,1.0,2,...,4,1,5033,2,2,72,1849,286,0,Coahuila
45275,1565438020,1,8,10,2,25,NaN,1,2.0,2,...,4,1,15005,4,1,308,5438,566,0,México

In [ ]:
#Se eliminan columnas con datos nulos o no incluidas en el análisis.

columnas_a_eliminar = caract_hogares.columns[[0, 6, 8, 14, 28, 34, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 77, 78, 79, 80, 81]]
caract_hogares = caract_hogares.drop(columns=columnas_a_eliminar)
caract_hogares.head()

,tipo_viv,mat_pared,mat_techos,mat_pisos,antiguedad,cocina,cuart_dorm,num_cuarto,lugar_coc,agua_ent,...,p_fractura,p_electric,p_tuberias,tot_resid,tot_hom,tot_muj,tot_hog,ubica_geo,tam_loc,entidad
0,7,8,10,3,30,1,1,4,1,2,...,2,2,2,4,2,2,1,1001,1,Aguascalientes
1,1,8,10,3,30,1,3,4,1,1,...,2,2,2,4,2,2,1,1001,1,Aguascalientes
2,1,8,10,3,,1,2,3,1,1,...,2,2,2,2,1,1,1,1001,1,Aguascalientes
3,1,8,10,3,25,1,2,3,1,1,...,2,2,2,4,3,1,1,1001,1,Aguascalientes
4,4,8,10,3,9,1,2,3,1,1,...,2,2,2,4,1,3,1,1001,1,Aguascalientes

In [ ]:
columnas = list(caract_hogares.columns)
columnas

['tipo_viv',
 'mat_pared',
 'mat_techos',
 'mat_pisos',
 'antiguedad',
 'cocina',
 'cuart_dorm',
 'num_cuarto',
 'lugar_coc',
 'agua_ent',
 'ab_agua',
 'dotac_agua',
 'excusado',
 'uso_compar',
 'sanit_agua',
 'biodigest',
 'bano_comp',
 'bano_excus',
 'bano_regad',
 'drenaje',
 'disp_elect',
 'focos',
 'focos_ahor',
 'combus',
 'eli_basura',
 'tenencia',
 'renta',
 'estim_pago',
 'pago_viv',
 'tipo_adqui',
 'viv_usada',
 'num_dueno1',
 'escrituras',
 'lavadero',
 'fregadero',
 'regadera',
 'tinaco_azo',
 'cisterna',
 'pileta',
 'calent_sol',
 'calent_gas',
 'calen_lena',
 'medid_luz',
 'bomba_agua',
 'tanque_gas',
 'aire_acond',
 'calefacc',
 'p_grietas',
 'p_pandeos',
 'p_levanta',
 'p_humedad',
 'p_fractura',
 'p_electric',
 'p_tuberias',
 'tot_resid',
 'tot_hom',
 'tot_muj',
 'tot_hog',
 'ubica_geo',
 'tam_loc',
 'entidad']

In [ ]:
# Se renombran las columnas para hacer más fácil la lectura a interesados no técnicos.

nuevos_nombres = {
    'tipo_viv': 'tipo_vivienda',
    'mat_pared': 'material_paredes',
    'mat_techos': 'material_techos',
    'mat_pisos': 'material_pisos',
    'antiguedad': 'antigüedad',
    'cocina': 'cocina',
    'cuart_dorm': 'cuarto_dormitorio',
    'num_cuarto': 'numero_cuartos',
    'lugar_coc': 'lugar_cocina',
    'agua_ent': 'lugar_agua',
    'ab_agua': 'origen_agua',
    'dotac_agua': 'agua_no_excl',
    'excusado': 'excusado',
    'uso_compar': 'uso_compartido',
    'sanit_agua': 'agua_sanitario',
    'biodigest': 'biodigestor',
    'bano_comp': 'bano_compartido',
    'bano_excus': 'bano_exclusivo',
    'bano_regad': 'bano_regadera',
    'drenaje': 'drenaje',
    'disp_elect': 'disp_electricidad',
    'focos': 'focos',
    'focos_ahor': 'focos_ahorradores',
    'combus': 'combustible_cocina',
    'eli_basura': 'manejo_basura',
    'tenencia': 'tenencia',
    'renta': 'renta',
    'estim_pago': 'estimacion_pago',
    'pago_viv': 'pago_vivienda',
    'tipo_adqui': 'tipo_adquisicion',
    'viv_usada': 'vivienda_usada',
    'num_dueno1': 'numero_dueno',
    'escrituras': 'escrituras',
    'lavadero': 'lavadero',
    'fregadero': 'fregadero',
    'regadera': 'regadera',
    'tinaco_azo': 'tinaco',
    'cisterna': 'cisterna',
    'pileta': 'pileta',
    'calent_sol': 'calentador_solar',
    'calent_gas': 'calentador_gas',
    'calen_lena': 'calentador_lena',
    'medid_luz': 'medidor_luz',
    'bomba_agua': 'bomba_agua',
    'tanque_gas': 'tanque_gas',
    'aire_acond': 'aire_acondicionado',
    'calefacc': 'calefacción',
    'p_grietas': 'grietas',
    'p_pandeos': 'pandeos',
    'p_levanta': 'levantamiento',
    'p_humedad': 'humedad',
    'p_fractura': 'fractura',
    'p_electric': 'electricidad',
    'p_tuberias': 'tuberías',
    'tot_resid': 'total_residentes',
    'tot_hom': 'total_hombres',
    'tot_muj': 'total_mujeres',
    'tot_hog': 'total_hogares',
    'ubica_geo': 'ubicacion_geografica',
    'tam_loc': 'tamano_localidad',
    'entidad': 'entidad'
}

caract_hogares = caract_hogares.rename(columns=nuevos_nombres)
caract_hogares.sample(10)

,tipo_vivienda,material_paredes,material_techos,material_pisos,antigüedad,cocina,cuarto_dormitorio,numero_cuartos,lugar_cocina,lugar_agua,...,fractura,electricidad,tuberías,total_residentes,total_hombres,total_mujeres,total_hogares,ubicacion_geografica,tamano_localidad,entidad
74080,1,8,2,3,5,1,3,4,1,1,...,2,2,2,3,2,1,1,26043,1,Sonora
53887,1,8,10,3,11,1,2,4,1,1,...,2,2,2,1,0,1,1,19041,2,Nuevo León
46205,1,8,10,3,21,1,3,7,1,1,...,2,2,2,1,1,0,1,16082,2,Michoacán
26615,5,8,4,2,,1,1,1,1,2,...,2,2,2,2,1,1,1,9005,1,Ciudad de México
46180,1,8,10,3,25,1,2,3,1,1,...,2,1,2,3,1,2,1,16076,2,Michoacán
46564,1,7,9,2,,1,2,4,1,1,...,2,2,2,4,2,2,1,16107,2,Michoacán
23270,1,8,10,3,20,1,2,5,1,1,...,2,1,2,3,0,3,1,8037,1,Chihuahua
7862,1,8,10,3,,1,3,4,1,1,...,2,2,2,4,2,2,1,3003,1,Baja California Sur
76342,2,8,10,3,28,1,2,4,1,1,...,2,1,2,2,1,1,1,27013,3,Tabasco
81676,1,8,10,2,12,1,2,3,1,1,...,2,2,2,5,2,3,1,29004,4,Tlaxcala

In [ ]:
columnas_nuevas = list(caract_hogares.columns)
columnas_nuevas

['tipo_vivienda',
 'material_paredes',
 'material_techos',
 'material_pisos',
 'antigüedad',
 'cocina',
 'cuarto_dormitorio',
 'numero_cuartos',
 'lugar_cocina',
 'lugar_agua',
 'origen_agua',
 'agua_no_excl',
 'excusado',
 'uso_compartido',
 'agua_sanitario',
 'biodigestor',
 'bano_compartido',
 'bano_exclusivo',
 'bano_regadera',
 'drenaje',
 'disp_electricidad',
 'focos',
 'focos_ahorradores',
 'combustible_cocina',
 'manejo_basura',
 'tenencia',
 'renta',
 'estimacion_pago',
 'pago_vivienda',
 'tipo_adquisicion',
 'vivienda_usada',
 'numero_dueno',
 'escrituras',
 'lavadero',
 'fregadero',
 'regadera',
 'tinaco',
 'cisterna',
 'pileta',
 'calentador_solar',
 'calentador_gas',
 'calentador_lena',
 'medidor_luz',
 'bomba_agua',
 'tanque_gas',
 'aire_acondicionado',
 'calefacción',
 'grietas',
 'pandeos',
 'levantamiento',
 'humedad',
 'fractura',
 'electricidad',
 'tuberías',
 'total_residentes',
 'total_hombres',
 'total_mujeres',
 'total_hogares',
 'ubicacion_geografica',
 'tamano_localidad',
 'entidad']

In [ ]:
#Exportación del nuevo dataframe limpio y modelado.
#A este punto, este df puede servir para su uso en herramientas de BI.

caract_hogares.to_csv("caract_hogares_limpio.csv", index=False, encoding='utf-8-sig')